<?php
/*
1. abs(): It returns the absolute (positive) value of a number.
syntax: abs(number);
Example: echo abs(-250);
output: 250
*/

/*
2. bindec(): It converts a binary number to its decimal equivalent.
syntax: bindec(binary_string);
Example: echo bindec("1010");
output: 10
*/

/*
3. decbin(): It converts a decimal number into binary.
syntax: decbin(number);
Example: var_dump(decbin(10));
output: "1010"
*/

/*
4. dechex(): It converts a decimal number into hexadecimal.
syntax: dechex(number);
Example: var_dump(dechex(255));
output: "FF"
*/

/*
5. hexdec(): It converts a hexadecimal number into decimal.
syntax: hexdec(hexadecimal_string);
Example: echo hexdec("FF");
output: 255
*/

/*
6. decoct(): It converts a decimal number into octal.
syntax: decoct(number);
Example: var_dump(decoct(15));
output: "17"
*/


/*
7. octdec(): It converts an octal number into decimal.
syntax: octdec(octal);
Example: echo octdec("17");
output: 15
*/


/*
8. deg2rad(): It converts an angle from degrees to radians.
syntax: deg2rad(degree);
Example: echo deg2rad(180);
output: 3.1415926535898
*/

/*
9. rad2deg(): It converts an angle from radians to degrees.
syntax: rad2deg(radian);
Example: echo rad2deg(3.1415926535898);
output: 180
*/

/*
10. ceil(): It rounds a number upward to the nearest integer.
syntax: ceil(number);
Example: echo ceil(5.02);
output: 6
*/
/*
11. floor(): It rounds a number downward to the nearest integer.
syntax: floor(number);
Example: echo floor(5.9);
output: 5
*/

/*
12. round(): It rounds a number to the nearest integer or to a specified number of decimal places.
syntax: round(number, precision);
Example1 : echo round(5.67);
output: 6
Example 2 : echo round(5.6789, 2);
Output: 5.68
*/

/*
13. max(): It returns the largest value from a list of numbers or an array.
syntax: max(value1, value2, ...);
Example: echo max(20, 40, 10, 80);
output: 80
Example : 
$numbers=[20, 40, 10];
echo max($numbers);
output:40
*/


/*
14. min(): It returns the smallest value from a list of numbers or an array.
syntax: min(value1, value2, ...);
Example1 : echo min(20, 40, 10, 80);
output: 10
*/

/*
15. pi(): It returns the value of π (pi).
syntax: pi();
Example1 : echo pi();
output:3.1415926535898; 
*/

/*
16. pow(): It calculates a number raised to the power of another number.
syntax: pow(base, exponent);
Example1 : echo pow(2, 5);
output: 32
*/

/*
17. sqrt(): It returns the square root of a number.
syntax: sqrt(number);
Example1 : echo sqrt(64);
output: 8
*/


/*
18. rand(): It generates a random integer.
syntax: rand(min, max);
Example1 : echo rand(1, 100);
output:20
*/

/*
19. getrandmax(): It returns the largest possible random number that can be generated by rand().
syntax: getrandmax();
Example1 : echo getrandmax();
output: 2147483647
*/
//  echo getrandmax();
?>